language: csharp  
sudo: required  
solution: SharpYNAB.sln
install:
  - nuget restore SharpYNAB.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
dist: trusty  
mono: none
dotnet: 1.0.3
script:  
  - ./build.sh --quiet verify
script:
- xbuild /p:Configuration=Release SharpYNAB.sln
- mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./SharpYNAB.Tests/bin/Release/SharpYNAB.Tests.dll