language: csharp  
sudo: required  
solution: SharpYNAB.sln
install:
  - nuget restore SharpYNAB.sln
dist: trusty  
mono: latest
dotnet: 1.0.3
install:
 - nuget install xunit.runner.console -Version 2.2.0 -OutputDirectory testrunner
script:  
 - ./build.sh --quiet verify
 
script:
 - mono ./testrunner/xunit.runner.console.2.2.0/tools/xunit.console.exe SharpYNAB.Tests/bin/Release/SharpYNAB.Tests.dll
 - dotnet restore
 - dotnet test SharpYNAB.Tests/SharpnYNAB.Tests.csproj -c Release -f netcoreapp1.1